from __future__ import annotations
from pathlib import Path
from datetime import datetime
import xml.etree.ElementTree as ET
from xml.dom import minidom

def write_cdb_attributes(cdb_root: Path, version: str = "1.2") -> Path:
    """
    Write CDB_Attributes.xml - main metadata file describing the CDB (OGC CDB 1.2).
    
    Args:
        cdb_root: Root directory of the CDB
        version: CDB specification version (default "1.2")
    
    Returns:
        Path to written file
    """
    root = ET.Element("CDB_Attributes")
    root.set("version", version)
    
    # General information
    general = ET.SubElement(root, "General")
    ET.SubElement(general, "Name").text = "Aphelion3D CDB"
    ET.SubElement(general, "Description").text = "CDB 1.2 generated by Aphelion3D tooling"
    ET.SubElement(general, "Created").text = datetime.now().isoformat()
    ET.SubElement(general, "Updated").text = datetime.now().isoformat()
    ET.SubElement(general, "Vendor").text = "AphelionWorld"
    ET.SubElement(general, "SpecificationVersion").text = version
    
    # Spatial Reference System (OGC CDB 1.2 uses WGS84)
    spatial_ref = ET.SubElement(root, "SpatialReferenceSystem")
    ET.SubElement(spatial_ref, "Horizontal").text = "WGS84"
    ET.SubElement(spatial_ref, "Vertical").text = "MSL"  # Mean Sea Level
    ET.SubElement(spatial_ref, "EPSG_Horizontal").text = "4326"
    ET.SubElement(spatial_ref, "EPSG_Vertical").text = "5703"  # MSL height
    
    # Extent (global by default)
    extent = ET.SubElement(root, "Extent")
    ET.SubElement(extent, "WestBound").text = "-180.0"
    ET.SubElement(extent, "EastBound").text = "180.0"
    ET.SubElement(extent, "SouthBound").text = "-90.0"
    ET.SubElement(extent, "NorthBound").text = "90.0"
    
    # Geocell Size (always 1° x 1° in CDB)
    geocell = ET.SubElement(root, "GeocellSize")
    ET.SubElement(geocell, "Longitude").text = "1.0"
    ET.SubElement(geocell, "Latitude").text = "1.0"
    
    # Datasets present (CDB 1.2 dataset codes)
    datasets = ET.SubElement(root, "Datasets")
    
    dataset_list = [
        (1, "Elevation", "Terrain elevation data", "GeoTIFF"),
        (101, "Imagery", "Satellite/aerial imagery", "GeoTIFF"),
        (200, "VectorData", "Vector features", "GeoPackage"),
        (206, "Buildings", "Building footprints and 3D data", "GeoPackage"),
        (400, "GeometricModels", "Geospecific 3D models", "OpenFlight"),
        (500, "GeotypicalModels", "Geotypical 3D models", "OpenFlight"),
    ]
    
    for code, name, description, format_type in dataset_list:
        ds = ET.SubElement(datasets, "Dataset")
        ET.SubElement(ds, "Code").text = str(code)
        ET.SubElement(ds, "Name").text = name
        ET.SubElement(ds, "Description").text = description
        ET.SubElement(ds, "Format").text = format_type
    
    # LOD information (CDB always has LOD 0-5)
    lods = ET.SubElement(root, "LODs")
    for lod in range(6):  # LOD 0-5
        lod_elem = ET.SubElement(lods, "LOD")
        ET.SubElement(lod_elem, "Level").text = str(lod)
        tiles_per_side = 2 ** lod
        ET.SubElement(lod_elem, "TilesPerGeocell").text = str(tiles_per_side)
        tile_size_deg = 1.0 / tiles_per_side
        ET.SubElement(lod_elem, "TileSize").text = f"{tile_size_deg:.10f}"
        ET.SubElement(lod_elem, "TilesPerGeocellTotal").text = str(tiles_per_side * tiles_per_side)
    
    # Coordinate System Details
    coords = ET.SubElement(root, "CoordinateSystem")
    ET.SubElement(coords, "Type").text = "Geodetic"
    ET.SubElement(coords, "Units").text = "Degrees (horizontal), Meters (vertical)"
    
    # Write pretty XML
    path = cdb_root / "Metadata" / "CDB_Attributes.xml"
    path.parent.mkdir(parents=True, exist_ok=True)
    
    xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    path.write_text(xml_str, encoding="utf-8")
    
    return path


def write_version_xml(cdb_root: Path, version: str = "1.2", increment: int = 0) -> Path:
    """
    Write Version.xml - tracks CDB version and incremental updates.
    
    Args:
        cdb_root: Root directory of the CDB
        version: CDB spec version (1.2)
        increment: Incremental update number
    
    Returns:
        Path to written file
    """
    root = ET.Element("Version")
    
    ET.SubElement(root, "Specification").text = version
    ET.SubElement(root, "SpecificationURI").text = "https://docs.ogc.org/is/15-113r6/15-113r6.html"
    ET.SubElement(root, "Increment").text = str(increment)
    ET.SubElement(root, "Updated").text = datetime.now().isoformat()
    ET.SubElement(root, "CreatedBy").text = "Aphelion3D"
    
    path = cdb_root / "Metadata" / "Version.xml"
    path.parent.mkdir(parents=True, exist_ok=True)
    
    xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    path.write_text(xml_str, encoding="utf-8")
    
    return path


def write_schema_xml(cdb_root: Path) -> Path:
    """
    Write Schema.xml - describes the CDB directory structure (OGC CDB 1.2).
    
    Args:
        cdb_root: Root directory of the CDB
    
    Returns:
        Path to written file
    """
    root = ET.Element("CDB_Schema")
    root.set("version", "1.2")
    
    # Directory structure
    structure = ET.SubElement(root, "Structure")
    
    folders = [
        ("Tiles", "Geocell-based tile data organized by dataset and LOD"),
        ("GTModel", "Geospecific and Geotypical model directories"),
        ("Metadata", "CDB metadata and configuration files"),
        ("Configuration", "Application-specific configuration"),
    ]
    
    for folder, description in folders:
        folder_elem = ET.SubElement(structure, "Folder")
        ET.SubElement(folder_elem, "Name").text = folder
        ET.SubElement(folder_elem, "Description").text = description
    
    # Tile directory naming convention
    naming = ET.SubElement(root, "TileNamingConvention")
    ET.SubElement(naming, "Format").text = "D{code}_{name}/LOD{level}/N{lat}E{lon}/U{u}_V{v}/{filename}"
    ET.SubElement(naming, "Example").text = "D101_Imagery/LOD5/N52E004/U00_V00/imagery.tif"
    
    # Dataset codes (CDB 1.2)
    codes = ET.SubElement(root, "DatasetCodes")
    
    dataset_defs = [
        (1, "Elevation", "Terrain elevation - primary dataset"),
        (2, "MinMaxElevation", "Minimum and maximum elevation metadata"),
        (10, "TerrainElevation", "Detailed terrain elevation"),
        (101, "Imagery", "RGB/RGBA satellite and aerial imagery"),
        (102, "Imagery_RGBA", "RGBA imagery with transparency"),
        (200, "VectorData", "Vector features (roads, buildings, etc.)"),
        (201, "Roads", "Road network vector data"),
        (202, "Railroads", "Railroad network data"),
        (203, "PowerLines", "Power line network data"),
        (204, "Hydrography", "Water features and hydrographic data"),
        (205, "Boundaries", "Political and administrative boundaries"),
        (206, "Buildings", "Building footprints and 3D geometry"),
        (207, "LandUse", "Land use classification data"),
        (208, "Trees", "Individual tree and forest data"),
        (300, "PointFeatures", "Point-based vector features"),
        (301, "Text", "Text labels and annotations"),
        (302, "RasterAttribution", "Raster-based attribute data"),
        (400, "GeometricModels", "Geospecific 3D models (OpenFlight)"),
        (500, "GeotypicalModels", "Geotypical 3D models (OpenFlight)"),
        (600, "Metadata", "Additional metadata files"),
    ]
    
    for code, name, desc in dataset_defs:
        ds = ET.SubElement(codes, "Dataset")
        ET.SubElement(ds, "Code").text = str(code)
        ET.SubElement(ds, "Name").text = name
        ET.SubElement(ds, "Description").text = desc
    
    # LOD specifications
    lods = ET.SubElement(root, "LODSpecifications")
    for lod in range(6):
        lod_elem = ET.SubElement(lods, "LOD")
        ET.SubElement(lod_elem, "Level").text = str(lod)
        ET.SubElement(lod_elem, "TilesPerSide").text = str(2 ** lod)
        ET.SubElement(lod_elem, "TileCount").text = str((2 ** lod) ** 2)
    
    path = cdb_root / "Metadata" / "Schema.xml"
    path.parent.mkdir(parents=True, exist_ok=True)
    
    xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    path.write_text(xml_str, encoding="utf-8")
    
    return path


def write_defaults_xml(cdb_root: Path) -> Path:
    """
    Write Defaults.xml - default settings and configurations.
    
    Args:
        cdb_root: Root directory of the CDB
    
    Returns:
        Path to written file
    """
    root = ET.Element("CDB_Defaults")
    root.set("version", "1.2")
    
    # Default material properties
    materials = ET.SubElement(root, "Materials")
    mat = ET.SubElement(materials, "Default")
    ET.SubElement(mat, "Ambient").text = "0.2 0.2 0.2 1.0"
    ET.SubElement(mat, "Diffuse").text = "0.8 0.8 0.8 1.0"
    ET.SubElement(mat, "Specular").text = "0.0 0.0 0.0 1.0"
    ET.SubElement(mat, "Shininess").text = "0.0"
    
    # Lighting
    lighting = ET.SubElement(root, "Lighting")
    ET.SubElement(lighting, "AmbientIntensity").text = "0.3"
    ET.SubElement(lighting, "DirectionalLightIntensity").text = "0.7"
    sun_pos = ET.SubElement(lighting, "SunPosition")
    ET.SubElement(sun_pos, "Azimuth").text = "45.0"
    ET.SubElement(sun_pos, "Elevation").text = "45.0"
    
    # Texture defaults
    textures = ET.SubElement(root, "Textures")
    ET.SubElement(textures, "DefaultFilter").text = "Linear"
    ET.SubElement(textures, "DefaultMipMapping").text = "true"
    
    # Performance settings
    performance = ET.SubElement(root, "Performance")
    ET.SubElement(performance, "DefaultLODRange").text = "100000"  # meters
    ET.SubElement(performance, "CullingEnabled").text = "true"
    
    path = cdb_root / "Configuration" / "Defaults.xml"
    path.parent.mkdir(parents=True, exist_ok=True)
    
    xml_str = minidom.parseString(ET.tostring(root)).toprettyxml(indent="  ")
    path.write_text(xml_str, encoding="utf-8")
    
    return path


def initialize_cdb_metadata(cdb_root: Path, version: str = "1.2") -> list[Path]:
    """
    Initialize all required CDB 1.2 metadata files.
    
    Args:
        cdb_root: Root directory of the CDB
        version: CDB specification version (default 1.2)
    
    Returns:
        List of paths to created metadata files
    """
    written = []
    
    # Create Schema subfolder inside Metadata
    schema_dir = cdb_root / "Metadata" / "Schema"
    schema_dir.mkdir(parents=True, exist_ok=True)
    
    written.append(write_cdb_attributes(cdb_root, version))
    written.append(write_version_xml(cdb_root, version))
    written.append(write_schema_xml(cdb_root))
    # written.append(write_defaults_xml(cdb_root))  # Skip to avoid creating Configuration folder
    
    return written